name: MudKingdom
version: '1.0.0'
main: com.mudkingdom.MudKingdom
api-version: '1.21'
author: Zewatara
description: A Minecraft plugin for MudKingdom

commands:
  mudkingdom:
    description: Main MudKingdom command
    usage: /<command> <config|areas>
    aliases: [mk, mud]

permissions:
  mudkingdom.areas:
    description: Access to areas commands
    default: op
  mudkingdom.config:
    description: Access to config commands
    default: op